hankook:
  politics:
    Politics: [HA01,HA02, HA03, HA04, HA99]
  economy:
    Economy: [HB01, HB02, HB03, HB04, HB05, HB99]
  international:
    World: [HD01, HD02, HD03, HD04, HD05, HD99]
  society:
    Society: [HC01, HC02, HC03, HC04, HC05, HC06, HC99]
  culture:
    Culture: [HE01, HE02, HE99]
  entertainment:
    Culture: [HF99, HF02, HF03, HF04, HF05, HF06]
  sports:
    Sports: [HG01, HG02, HG03, HG04, HG05, HG06, HG99]

donga:
  politics:
    Politics: [CWD, NA, NK, Dip, Admin]
  economy:
    Economy: [CEO, RE, Money, It/List, Car]
  international:
    Inter: [Asia, USA, EU, China, Japan]
  society:
    Society: [Series/70030000000919, Series/70030000000923, Edu, Labor, Event]
  culture:
    Culture: [Liter, Health, Food, Fashion, Travel]
  entertainment:
    Entertainment: [TV, Movie, Music]
  sports:
    Sports: [Base, Foot, Golf, Basket]


chosun:
  politics:
    politics: [politics_general, blue_house, assembly, north_korea, diplomacy-defense, goverment]
  economy:
    economy: [economy_general, science, int_economy, money, real_estate, industry-company, market_trend, startup_story, auto, smb-venture, tech_it, weeklybiz]
  international:
    international: [international_general, us, china, japan, asia, europe, mideast-africa-latin, topic]
  society:
    national: [national_general, incident, court_law, education, labor, transport-environment, welfare-medical, jobs, people, obituary-personnel, nie, weekend]
  culture:
    culture-life: [culture_general, book, movie_review, music_concert, performance-arts, art-gallery, relion-academia, broadcast-media, archi-design, fashion-beauty, travel, food-taste, health, living]
  entertainment:
    entertainments: [enter_general, celebrity, broadcast, movie, music, entertain_photo]
  sports:
    sports: [sports_general, baseball, world-baseball, football, world-football, basketball, volleyball, golf, sports_photo]

seoul:
  politics:
    politics: [president, congress, north, diplomacy]
  economy:
    economy: [industry, house, money, car, distribution, trade, it, policy, sbiz_biz]
  international:
    internationa: [natEconomy, china, japan, africa, asia, usa, eiurope, internation_topic, glo_insight]
  society:
    society: [accident, law, envrionment, Edu, science1, health100, welfare]
  culture:
    life: [music, scholaship, exhibition, book, public_culture, religion2, LetsGo, helath2, munhoa, pets_cats, screen, performance]
  entertainment:
    entertainment: [broadcastN, movieN, foreigncountryN, musicN, starinterN]
  sports:
    sport: [baseball, soccer, golf, basketball, volleyball]

joongang:
  politics:
    politics: [general, assemgov, bluehouse, deplomacy, nk, northkorea]
  economy:
    money: [general, economicpolicy, industry, finance, realestate, science, labor, globaleconomy]
  international:
    world: [general, northame, china, japan, eu, etc]
  society:
    society: [general, accident, lawa, education, welfare, helathcare, environment, traffic, national]
  culture:
    culture: [general, book, exhibition, performance, song, movie, broadcast]
  entertainment:
  sports:
    sports: [general, baseball, soccer, golf, basketvolley]
